description: Ensure go formatting is correct.
executor: go-machine
steps:
  - checkout
  # Setup Go enabling the proxy for downloading modules.
  - setup-go:
      GOPROXY: https://proxy.golang.org,direct
  - run:
      name: make fmt
      command: |
        go install "mvdan.cc/gofumpt@v${GOFUMPT_VERSION}"
        make fmt
        if ! git diff --exit-code; then
          echo "Code has formatting errors. Run 'make fmt' to fix"
          exit 1
        fi
