---
executor: alpine 
steps:
  - setup-semgrep
  - checkout
  - attach_workspace:
      at: .
  - run:
      name: Run Semgrep Rules
      command: |
        # Alpine images can't run the make file due to a bash requirement. Run
        # semgrep explicitly here. 
        export PATH="$HOME/.local/bin:$PATH" 
        semgrep --error --include '*.go' --exclude 'vendor' -f tools/semgrep/ci .
