references:
  environment: &ENVIRONMENT
    CIRCLECI_CLI_VERSION: 0.1.5546 # Pin CircleCI CLI to patch version (ex: 1.2.3)
    GOTESTSUM_VERSION: 0.5.2 # Pin gotestsum to patch version (ex: 1.2.3)
    GOFUMPT_VERSION: 0.3.1 # Pin gofumpt to patch version (ex: 1.2.3)
    GO_TAGS: ""
    GO_IMAGE: &GO_IMAGE "docker.mirror.hashicorp.services/cimg/go:1.20"
go-machine:
  machine:
    image: ubuntu-2004:2022.10.1
  environment: *ENVIRONMENT
  shell: /usr/bin/env bash -euo pipefail -c
  working_directory: /home/circleci/go/src/github.com/hashicorp/vault
node:
  docker:
    - image: docker.mirror.hashicorp.services/circleci/node:14-browsers
      environment:
        # See https://git.io/vdao3 for details.
        JOBS: 2
  shell: /usr/bin/env bash -euo pipefail -c
  working_directory: /home/circleci/go/src/github.com/hashicorp/vault
python:
  docker:
    - image: docker.mirror.hashicorp.services/python:3-alpine
  shell: /usr/bin/env bash -euo pipefail -c
  working_directory: /home/circleci/go/src/github.com/hashicorp/vault
semgrep:
  docker:
    - image: docker.mirror.hashicorp.services/returntocorp/semgrep:0.113.0
  shell: /bin/sh
  working_directory: /home/circleci/go/src/github.com/hashicorp/vault
docker-env-go-test-remote-docker:
  resource_class: medium
  docker:
    - image: *GO_IMAGE
  environment: *ENVIRONMENT
  working_directory: /home/circleci/go/src/github.com/hashicorp/vault
docker-env-go-test:
  resource_class: large
  docker:
    - image: *GO_IMAGE
  environment: *ENVIRONMENT
  working_directory: /home/circleci/go/src/github.com/hashicorp/vault
docker-env-go-test-race:
  resource_class: xlarge
  docker:
    - image: *GO_IMAGE
  environment: *ENVIRONMENT
  working_directory: /home/circleci/go/src/github.com/hashicorp/vault
