go-machine:
  machine: true
  shell: /usr/bin/env bash -euo pipefail -c
  environment:
    GO111MODULE: "off"
    CIRCLECI_CLI_VERSION: 0.1.5546  # Pin CircleCI CLI to patch version (ex: 1.2.3)
    GO_VERSION: 1.15.10  # Pin Go to patch version (ex: 1.2.3)
    GOTESTSUM_VERSION: 0.5.2  # Pin gotestsum to patch version (ex: 1.2.3)
    GO_TAGS: ""
  working_directory: /go/src/github.com/hashicorp/vault
node:
  docker:
    - image: docker.mirror.hashicorp.services/node:10-buster
  shell: /usr/bin/env bash -euo pipefail -c
  working_directory: /go/src/github.com/hashicorp/vault
python:
  docker:
    - image: docker.mirror.hashicorp.services/python:3-alpine
  shell: /usr/bin/env bash -euo pipefail -c
  working_directory: /go/src/github.com/hashicorp/vault
alpine:
  docker:
    - image: docker.mirror.hashicorp.services/alpine:3.10.2
  shell: /bin/sh
  working_directory: /go/src/github.com/hashicorp/vault
docker-env-go-test-remote-docker:
  resource_class: medium
  docker:
    - image: "docker.mirror.hashicorp.services/circleci/golang:1.15.4-buster"
  environment:
    GO111MODULE: "off"
    CIRCLECI_CLI_VERSION: 0.1.5546  # Pin CircleCI CLI to patch version (ex: 1.2.3)
    GO_TAGS: ""
  working_directory: /go/src/github.com/hashicorp/vault
docker-env-go-test:
  resource_class: large
  docker:
    - image: "docker.mirror.hashicorp.services/circleci/golang:1.15.4-buster"
  environment:
    GO111MODULE: "off"
    CIRCLECI_CLI_VERSION: 0.1.5546  # Pin CircleCI CLI to patch version (ex: 1.2.3)
    GO_TAGS: ""
  working_directory: /go/src/github.com/hashicorp/vault
docker-env-go-test-race:
  resource_class: xlarge
  docker:
    - image: "docker.mirror.hashicorp.services/circleci/golang:1.15.4-buster"
  environment:
    GO111MODULE: "off"
    CIRCLECI_CLI_VERSION: 0.1.5546  # Pin CircleCI CLI to patch version (ex: 1.2.3)
    GO_TAGS: ""
  working_directory: /go/src/github.com/hashicorp/vault
