description: >
  Check if branch name starts with ui/ or docs/ and if so, exit.
steps:
  - run:
      working_directory: ~/
      name: Check branch name
      command: |
        # If the branch being tested starts with ui/ or docs/ we want to exit the job without failing
        [[ "$CIRCLE_BRANCH" = ui/* || "$CIRCLE_BRANCH" = docs/* || "$CIRCLE_BRANCH" = backport/docs/* ]] && {
          # stop the job from this step
          circleci-agent step halt
        }
        # exit with success either way
        exit 0
