description: >
  Check if branch name starts with ui/ or docs/ and if so, exit.
steps:
  - run:
      working_directory: ~/
      name: Check branch name
      command: |
        case "$CIRCLE_BRANCH" in
        main|ui/*|backport/ui/*|release/*|merge*) ;;
        *) # If the branch being tested doesn't match one of the above patterns,
           # we don't need to run test-ui and can abort the job.
           circleci-agent step halt
           ;;
        esac

        # exit with success either way
        exit 0
