language: go

sudo: false

cache:
  directories:
    - $HOME/.ccm/repository

matrix:
  fast_finish: true

env:
  global:
    - GOMAXPROCS=2
  matrix:
    - CASS=1.2.19 AUTH=false
    - CASS=2.0.14 AUTH=false
    - CASS=2.1.5  AUTH=false
    - CASS=2.1.5  AUTH=true

go:
  - 1.3
  - 1.4

install:
  - pip install --user cql PyYAML six
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/cover
  - git clone https://github.com/pcmanus/ccm.git
  - pushd ccm
  - ./setup.py install --user
  - popd
  - go get .

script:
  - set -e
  - go test -v -tags unit
  - PATH=$PATH:$HOME/.local/bin bash -x integration.sh $CASS $AUTH
  - go vet .

notifications:
  - email: false
