language: go

sudo: false

cache:
  directories:
    - $HOME/.ccm/repository

matrix:
  fast_finish: true

env:
  global:
    - GOMAXPROCS=2
  matrix:
    - CASS=2.0.17
      AUTH=false
    - CASS=2.1.11
      AUTH=false
    - CASS=2.1.11
      AUTH=true
    - CASS=2.2.3
      AUTH=false

go:
  - 1.4
  - 1.5

install:
  - pip install --user cql PyYAML six
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/cover
  - git clone https://github.com/pcmanus/ccm.git
  - pushd ccm
  - ./setup.py install --user
  - popd
  - go get .

script:
  - set -e
  - go test -v -tags unit
  - PATH=$PATH:$HOME/.local/bin bash integration.sh $CASS $AUTH
  - go vet .

notifications:
  - email: false
