# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

contact_links:
  - name: Ask a question
    url: https://discuss.hashicorp.com/c/vault
    about: For increased visibility, please post questions on the discussion forum.
