jobs:
  - pre-flight-checks
  - install-ui-dependencies:
      requires:
        - pre-flight-checks
  - build-go-dev:
      requires:
        - pre-flight-checks
  - test-ui:
      requires:
        - install-ui-dependencies
        - build-go-dev
        # Only master, UI, release and merge branches need to run UI tests.
        # We don't filter here however because test-ui is configured in github as
        # required so it must run, instead we short-circuit within test-ui.
  - test-ui-browserstack:
      requires:
        - install-ui-dependencies
        - build-go-dev
      filters:
        branches:
          # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
          ignore: /pull\/[0-9]+/
  - test-go:
      requires:
        - pre-flight-checks
      # We don't filter here because this is a required CI check;
      # instead we short-circuit within the test command so it ends quickly.
  - test-go-remote-docker:
      requires:
        - pre-flight-checks
      # We don't filter here because this is a required CI check;
      # instead we short-circuit within the test command so it ends quickly.
  - test-go-race:
      requires:
        - pre-flight-checks
      filters:
        branches:
          # UI and Docs-only branches should skip go tests
          ignore:
            - /^docs\/.*/
            - /^ui\/.*/
  - test-go-race-remote-docker:
      requires:
        - pre-flight-checks
      filters:
        branches:
          # UI and Docs-only branches should skip go tests
          ignore:
            - /^docs\/.*/
            - /^ui\/.*/
  - website-docker-image:
      context: vault-docs
      filters:
        branches:
          only:
            - master
  - algolia-index:
      context: vault-docs
      filters:
        branches:
          only:
            - stable-website
