jobs:
  - pre-flight-checks
  - install-ui-dependencies:
      requires:
        - pre-flight-checks
  - build-go-dev:
      requires:
        - pre-flight-checks
  - go-mod-vendor:
      requires:
        - pre-flight-checks
  - test-ui:
      requires:
        - install-ui-dependencies
        - build-go-dev
      filters:
        branches:
          only:
            - /^ui\/.*/
            - master
            - /release\/.*/
  - test-ui-browserstack:
      requires:
        - install-ui-dependencies
        - build-go-dev
      filters:
        branches:
          # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
          ignore: /pull\/[0-9]+/
  - test-go:
      requires:
        - pre-flight-checks
  - test-go-remote-docker:
      requires:
        - pre-flight-checks
  - test-go-race:
      requires:
        - pre-flight-checks
      filters:
        branches:
          # UI and Docs-only branches should skip go tests
          ignore:
            - /^docs\/.*/
            - /^ui\/.*/
  - test-go-race-remote-docker:
      requires:
        - pre-flight-checks
      filters:
        branches:
          # UI and Docs-only branches should skip go tests
          ignore:
            - /^docs\/.*/
            - /^ui\/.*/
  - website-docker-image:
      context: vault-docs
      filters:
        branches:
          only:
            - master
  - algolia-index:
      context: vault-docs
      filters:
        branches:
          only:
            - stable-website
