
# This file sets configuration for Netlify
# ref: https://www.netlify.com/docs/netlify-toml-reference/

[build]
  publish = "out"
  command = "npm run static"

[context.production]
  environment = { HASHI_ENV = "production", NODE_ENV = "production"}

[context.deploy-preview]
  environment = { HASHI_ENV = "staging" }

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
