name: Legacy Link Format Checker

on:
  push:
    paths:
      - "website/content/**/*.mdx"
      - "website/data/*-nav-data.json"

jobs:
  check-links:
    uses: hashicorp/dev-portal/.github/workflows/docs-content-check-legacy-links-format.yml@475289345d312552b745224b46895f51cc5fc490
    with:
      repo-owner: "hashicorp"
      repo-name: "vault"
      commit-sha: ${{ github.sha }}
      mdx-directory: "website/content"
      nav-data-directory: "website/data"
