name: Check Copywrite Headers

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
      - release/**

jobs:
  copywrite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: hashicorp/setup-copywrite@v1.1.3
        name: Setup Copywrite
        with:
          version: v0.16.4
          archive-checksum: c299f830e6eef7e126a3c6ef99ac6f43a3c132d830c769e0d36fa347fa1af254
      - name: Check Header Compliance
        run: make ci-copywriteheaders
permissions:
  contents: read
