on:
  pull_request:
    branches:
      - master

jobs:
  insist_milestone:
    name: Complain if a milestone isn't set
    # Don't need the expression syntax in the if
    # The if should stop the job from running
    if: github.event.pull_request.milestone == {}
    steps:
    - name: Dump some info
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
