name: Check Functions For nil, nil returns

on:
  pull_request:
    types: [opened, synchronize]
    # Runs on PRs to main
    branches:
      - main

jobs:
  # Note: if there is a function we want to ignore this check for,
  # You can add 'ignore-nil-nil-function-check' somewhere in the
  # godoc for the function.
  nil-nil-function-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0
      - name: Set Up Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          cache: true
          go-version-file: ./.go-version
      - name: Verify functions don't return nil, nil
        run: make ci-vet-gonilnilfunctions
