name: Check Functions For nil, nil returns

on:
  pull_request:
    types: [opened, synchronize]
    # Runs on PRs to main
    branches:
      - main

jobs:
  godoc-test-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0
      - name: Set Up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          cache: true
          go-version-file: ./.go-version
      - name: Verify functions don't return nil, nil
        run: make ci-vet-gonilnilfunctions
