name: sustain

on:
  issues:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      PROJECT_COLUMN_ID: ${{secrets.PROJECT_COLUMN_ID}}
    steps:
    - name: Maybe move an issue to the project board
      uses: actions/github-script@0.4.0
      if: github.event.label.name == 'bug'
      with: 
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |            
            github.projects.createCard({
              column_id: process.env.PROJECT_COLUMN_ID,
              content_id: context.payload.issue.id,
              content_type: "Issue"
            })